### PR TITLE
[WIP][DO NOT MERGE] Update to upstream Rust as of 2018-12-19

### PR DESCRIPTION
**Pull request by dylanmckay**
Tracked by avr-rust/rust#122.

### CODE REVIEW

**Comment by shepmaster** [comment]
fwiw ive been squashing the readme commits into one master readme commit

**Comment by dylanmckay** [comment]
I will do so too

**Comment by dylanmckay** [comment]
I've updated the LLVM submodule, squashed the README update, and it builds successfully.

**Comment by dylanmckay** [comment]
Fixed a few rustfmt errors and added tests for `avr-interrupt` that are now required for anything with a feature gate.

**Comment by dylanmckay** [comment]
Done, force pushed.

**Pull request closed without merging**
